### ISSUE TITLE
Command stub in guards and notifiactions

### ISSUE THREAD

**Issue by joerg** [sethvargo/chefspec#613] opened 2015-07-23 09:33 UTC
I am having problems testing notifications on a resource that is guarded with a command.

Recipe
```
execute 'Download RPM' do
  command <<-CMD
    yumdownloader --destdir #{settings['cache_path']} my-package
    rpm -i --noscripts #{settings['cache_path']}/my-package*.rpm
  CMD
  not_if 'rpm -q my-package'
  notifies :run, 'ruby_block[Set my-package owner]', :immediately
end

ruby_block 'Set my-package owner' do
  block do
    my_package_dir = File.join(settings['rootdir'], 'my-package')
    FileUtils.chown_R owner_user, owner_group, my_package_dir
  end
  action :nothing
end
```

Now depending on the guards return value I want to check if a notification is sent:
```
describe 'rcrs-sas-install::_sas_setup' do
  let(:chef_run) do
    ChefSpec::ServerRunner.new(file_cache_path: '/tmp/chef/cache') do |node, server|
      server.create_data_bag('sas_host_configurations', {})
      node.automatic['ipaddress'] = '12.34.56.78'
    end.converge(described_recipe)
  end

  context 'my-package is not yet installed' do
    before(:each) do
      stub_command("rpm -q my-package").and_return(false)
    end

    it 'expects to set my-package owner afterwards' do
      expect(chef_run.execute('Download RPM')).to notify('ruby_block[Set my-package owner]').to(:run).immediately
    end
  end

  context 'JBoss is already installed' do
    it 'expects to not set JBoss owner' do
      stub_command('rpm -q JBoss-AS').and_return(false)
      expect(chef_run).to_not run_ruby_block('Set JBoss owner')
    end
  end
end
```

The second test is actually something I also tried, that is checking if the ruby_block is every run. I had no luck so far and it seems to me that the stub_command is actually completely ignored when it comes to checking for the notification.
Any ideas? Is this actually a bug?

**Comment by joerg** [comment] 2015-07-23 12:27
I just checked if my execute is run depending on the stubbed not_if but from chefspecs perspective it seems that the execute is always run, no matter what the stubbed command returns.

Almost forgot: I am using the latest Chef-dk with chefspec 4.2.0. I also tried with 4.3.0 but had the same results.

**Comment by sethvargo** [comment] 2015-07-23 14:42
@joerg that's because it's sees the resource - you need to inspect if it took any action though.

**Comment by joerg** [comment] 2015-07-23 14:51
I am not sure what you mean. Is it
```
expect(chef_run).to run_execute('Set my-program owner')
```

This always fails in any context.

**Comment by sethvargo** [comment] 2015-07-23 14:58
Yea, I'm not really sure, and I don't have time to dig in at the moment. It doesn't look like a bug, especially since no one else has reported the issue, but I suspect there's something subtle going on.

**Comment by joerg** [comment] 2015-07-24 07:19
I appreciate any help. I compiled a small example cookbook which fails in exactly this way. You can find the recipe and spec here: https://gist.github.com/joerg/19dd03dd20d31ee5409d. The recipe has only these two files in their directories and a metadata.rb.
The error it trows is:
```
..F.F.

Failures:

  1) chefspec-notifiy::default test_condition_command returns true and touches file /tmp/notified
     Failure/Error: expect(chef_run).to touch_file('/tmp/notified') # <- Does not work!
       expected "file[/tmp/notified]" actions [] to include :touch
     # ./spec/default_spec.rb:22:in `block (3 levels) in <top (required)>'

  2) chefspec-notifiy::default test_condition_command returns false and does not notify file /tmp/notified
     Failure/Error: expect(chef_run.execute('Notifier')).to_not notify('file[/tmp/notified]').to(:touch) # <- Does not work
       expected "execute[Notifier]" to not notify "file[/tmp/notified]", but it did.
     # ./spec/default_spec.rb:36:in `block (3 levels) in <top (required)>'

Finished in 0.30993 seconds (files took 4.95 seconds to load)
6 examples, 2 failures

Failed examples:

rspec ./spec/default_spec.rb:21 # chefspec-notifiy::default test_condition_command returns true and touches file /tmp/notified
rspec ./spec/default_spec.rb:35 # chefspec-notifiy::default test_condition_command returns false and does not notify file /tmp/notified
```

**Comment by sethvargo** [comment] 2015-07-27 01:35
This looks like a duplicate of https://github.com/sethvargo/chefspec/issues/541 as far as the notifications are concerned. In ChefSpec, you are asserting that the notification was written, not that action was taken. There's no way to actually test that a notification fired (there's no hook in Chef that ChefSpec can use). So you're testing "did I tell the resource to notify on change" not "did the resource notify". So that explains the confusion on that.

The second issue is somewhat related and equally confusing. ChefSpec writes all actions to noop. ChefSpec is really just a giant registry of the before + after Chef run. When you give a resource an action of "nothing", it will always have the action of "nothing", regardless of the notifications because the notifications won't fire (because Chef doesn't actually run). 

The behavior used to try and fake notification firing, but that caused more problems and confusion, so now notifications aren't run at all. Does that make sense?

Remember that ChefSpec isn't an integration framework. If you want to test this at a higher level, I would recommend Test Kitchen. Thanks!

**Closed by sethvargo** 2015-07-27 01:35 UTC

**Comment by joerg** [comment] 2015-07-27 06:46
Ok, now I understand. Thanks for clarifying that.
We are already using kitchen but we can't stub checks like "rpm -q ..." in kitchen which means we cant test seconds runs (first run installs and fires some execute, second run should do nothing). I was hoping chefspec could do so.

**Comment by sethvargo** [comment] 2015-07-27 13:33
Chef doesn't really provide a way to fire those notifications, so no :frowning:. I would consider refactoring your code to rely less on notifications (I personally find notifications are unintuitive and difficult to follow). Usually you can refactor the code to be more declarative without notfications.
