### ISSUE TITLE
covering one lwrp resource adds two more.

### ISSUE THREAD

**Issue by cpakman** [sethvargo/chefspec#603] opened 2015-06-07 19:12 UTC
I have an LWRP, with the provider roughly:

```ruby
action :install do
  temp_dir = ::File.join(Chef::Config[:file_cache_path], 'kraken')
  install_dir = "/opt/kraken_#{new_resource.port}"
  unless ::File.exist?("/opt/kraken_#{new_resource.port}/version") &&
         new_resource.revision == ::File.read(
           ::File.join(install_dir, "version")).strip

    directory "#{Chef::Config[:file_cache_path]}/kraken" do
      action :delete
      recursive true
    end

    git "#{Chef::Config[:file_cache_path]}/kraken" do
      repository new_resource.repository
      revision new_resource.revision
      action :sync
    end
  end
end
```

I added a test:

```ruby
let(:chef_run) do
  runner = ChefSpec::SoloRunner.new(platform: 'ubuntu',
                                      version: '14.04',
                                      step_into: ['asana_pubsub_kraken'])
  runner.converge(described_recipe)
end

it 'should make sure build directory is gone if executing LWRP' do
  expect(chef_run).to delete_directory(
    "#{Chef::Config[:file_cache_path]}/kraken")
end
```

it went from 3/10 resources (I have other stuff too) -> 4/12 resources. I copied in the same test multiple times, and I get 5/14, 6/16... etc. and I have no idea what's going on here.

**Comment by sethvargo** [comment] 2015-06-08 13:33
Hi @cpakman 

You are stepping into the resource, so it is executing those subsequent resources (you have two resources - `directory` and `git`) in the LWRP. You aren't touching those two resources, so the code coverage is correct.

As for the double-reporting - this is because you have a top-level compile-time check:

```ruby
  unless ::File.exist?("/opt/kraken_#{new_resource.port}/version") &&
         new_resource.revision == ::File.read(
           ::File.join(install_dir, "version")).strip
```

This runs _at compile time_, which changes the resource collection.

I am going to close this issue since it is not a bug, but I am happy to continue discussion.

**Closed by sethvargo** 2015-06-08 13:33 UTC

**Comment by cpakman** [comment] 2015-06-08 14:41
Hey @sethvargo - I really appreciate the quick response, but I'm still a little confused. I only converge the recipe once, so I don't see how including
```
it 'should make sure build directory is gone if executing LWRP' do
  expect(chef_run).to delete_directory(
    "#{Chef::Config[:file_cache_path]}/kraken")
end```

different numbers of times would cause the total number of resources to change, since from my limited understanding of chefspec, compile time is essentially happening at the `runner.converge()` step. I also _think_ that the above test touches one of those two resources (and seems to be the case since every time I add it, one more resource is touched.)

**Comment by sethvargo** [comment] 2015-06-08 15:00
@cpakman it is because that block is getting evaluated each time when you step_into the LWRP.

**Comment by cpakman** [comment] 2015-06-08 15:04
but as far as I can tell, I only step into it once?

**Comment by sethvargo** [comment] 2015-06-08 15:19
@cpakman you step into it each time you call `chef_run`

**Comment by cpakman** [comment] 2015-06-08 15:23
oh... I see now, thanks @sethvargo. last question: how would I test both resources and step into it only once? (also, I'm new to both ruby/rspec chef/chefspec, so sorry for the dumb questions).

**Comment by sethvargo** [comment] 2015-06-08 15:26
You need to use context blocks
