### ISSUE TITLE
chefspec cannot notify resources when action :nothing

### ISSUE THREAD

**Issue by topia** [sethvargo/chefspec#570] opened 2015-03-04 10:17 UTC
chefspec ignores notifies when default action is `:nothing`.
I created repository to reproduce, so you can clone it and `chef exec rspec` to verify.
Could you confirm it as bug, or by design?

https://github.com/topia/chefspec-notification-bug-explain

recipe:
https://github.com/topia/chefspec-notification-bug-explain/blob/master/recipes/default.rb
it should run `ruby_block[test]` -> `ruby_block[step1]` -> `ruby_block[step2]` when converge.

but current chefspec:
https://github.com/topia/chefspec-notification-bug-explain/blob/master/spec/test_actual_spec.rb
chefspec says step1 and step2 are not covered.

when `updated_by_last_action(true)` called on `perform_action`:
https://github.com/topia/chefspec-notification-bug-explain/blob/master/spec/test_expected_spec.rb#L9
it seems to good for me.

environment:
```
% chef -v
Chef Development Kit Version: 0.4.0
% chef gem list chefspec

*** LOCAL GEMS ***

chefspec (4.2.0)
```

**Comment by sethvargo** [comment] 2015-03-04 15:08
This is a duplicate of https://github.com/sethvargo/chefspec/issues/541. This is the expected behavior :smile:

**Closed by sethvargo** 2015-03-04 15:08 UTC

**Comment by topia** [comment] 2015-03-04 18:21
Hmm.
I think we can stub run_action with "mark as updated". but you don't think that, do you?
